package com.splxtech.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Appliance;
import greendao.WasteTypeBean;

import com.splxtech.dao.ApplianceDao;
import com.splxtech.dao.WasteTypeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig applianceDaoConfig;
    private final DaoConfig wasteTypeBeanDaoConfig;

    private final ApplianceDao applianceDao;
    private final WasteTypeBeanDao wasteTypeBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        applianceDaoConfig = daoConfigMap.get(ApplianceDao.class).clone();
        applianceDaoConfig.initIdentityScope(type);

        wasteTypeBeanDaoConfig = daoConfigMap.get(WasteTypeBeanDao.class).clone();
        wasteTypeBeanDaoConfig.initIdentityScope(type);

        applianceDao = new ApplianceDao(applianceDaoConfig, this);
        wasteTypeBeanDao = new WasteTypeBeanDao(wasteTypeBeanDaoConfig, this);

        registerDao(Appliance.class, applianceDao);
        registerDao(WasteTypeBean.class, wasteTypeBeanDao);
    }
    
    public void clear() {
        applianceDaoConfig.getIdentityScope().clear();
        wasteTypeBeanDaoConfig.getIdentityScope().clear();
    }

    public ApplianceDao getApplianceDao() {
        return applianceDao;
    }

    public WasteTypeBeanDao getWasteTypeBeanDao() {
        return wasteTypeBeanDao;
    }

}
