package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table APPLIANCE.
 */
public class Appliance {

    private Long id;
    private String name;
    private Integer imageId1;
    private Integer imageId2;
    private Integer appId;
    private Integer time;
    private Integer waste;
    private Boolean online;

    public Appliance() {
    }

    public Appliance(Long id) {
        this.id = id;
    }

    public Appliance(Long id, String name, Integer imageId1, Integer imageId2, Integer appId, Integer time, Integer waste, Boolean online) {
        this.id = id;
        this.name = name;
        this.imageId1 = imageId1;
        this.imageId2 = imageId2;
        this.appId = appId;
        this.time = time;
        this.waste = waste;
        this.online = online;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getImageId()
    {
        if(online==true)
        {
            return imageId1;
        }
        else
        {
            return imageId2;
        }
    }
    public Integer getImageId1() {
        return imageId1;
    }

    public void setImageId1(Integer imageId1) {
        this.imageId1 = imageId1;
    }

    public Integer getImageId2() {
        return imageId2;
    }

    public void setImageId2(Integer imageId2) {
        this.imageId2 = imageId2;
    }

    public Integer getAppId() {
        return appId;
    }

    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    public Integer getTime() {
        return time;
    }

    public void setTime(Integer time) {
        this.time = time;
    }

    public Integer getWaste() {
        return waste;
    }

    public void setWaste(Integer waste) {
        this.waste = waste;
    }

    public Boolean getOnline() {
        return online;
    }

    public void setOnline(Boolean online) {
        this.online = online;
    }

}
